/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ingolfur' at '10/29/14 1:06 PM' with Gradle 2.1
 *
 * @author ingolfur, @date 10/29/14 1:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
